name: Hello Workflow

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Hello step
        run: |
         echo "this is line 1"
         echo "this is line2"
