nname: Hello Code

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Step
        run: echo "This is build"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test Step
        run: echo "This is test"

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Step
        run: echo "This is deploy"   

        
 
